CREATE TABLE "census_records" (
  "record_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "census_year" int,
  "person_id" int,
  "source_pk" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "occupations" (
  "occupation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attribute_id" int,
  "person_id" int,
  "work" varchar(45),
  "business" varchar(45),
  "record_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "marital_levels" (
  "marital_level_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attribute_id" int,
  "person_id" int,
  "marital_status" varchar(45),
  "record_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "property_ownership" (
  "ownership_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attribute_id" int,
  "person_id" int,
  "owned_rented" varchar(45),
  "record_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "personal_attributes" (
  "attribute_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "race" varchar(45),
  "sex" varchar(45),
  "age" int,
  "record_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "persons" (
  "person_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(45),
  "last_name" varchar(45),
  "personal_attribute_id" int,
  "family_id" int,
  "relationship_id" int,
  "marital_level_id" int,
  "property_ownership_id" int,
  "occupation_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "relationships" (
  "relationship_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attribute_id" int,
  "person_id" int,
  "family_id" int,
  "relation_to_hoh" varchar(45),
  "record_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "families" (
  "family_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "family" int,
  "dwelling" int,
  "hoh_first_name" varchar(45),
  "hoh_last_name" varchar(45),
  "relationship_id" int,
  "census_year" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

ALTER TABLE "occupations" ADD FOREIGN KEY ("record_id") REFERENCES "census_records" ("record_id");

ALTER TABLE "marital_levels" ADD FOREIGN KEY ("record_id") REFERENCES "census_records" ("record_id");

ALTER TABLE "property_ownership" ADD FOREIGN KEY ("record_id") REFERENCES "census_records" ("record_id");

ALTER TABLE "personal_attributes" ADD FOREIGN KEY ("record_id") REFERENCES "census_records" ("record_id");

ALTER TABLE "persons" ADD FOREIGN KEY ("personal_attribute_id") REFERENCES "personal_attributes" ("attribute_id");

ALTER TABLE "persons" ADD FOREIGN KEY ("marital_level_id") REFERENCES "marital_levels" ("marital_level_id");

ALTER TABLE "persons" ADD FOREIGN KEY ("property_ownership_id") REFERENCES "property_ownership" ("ownership_id");

ALTER TABLE "persons" ADD FOREIGN KEY ("occupation_id") REFERENCES "occupations" ("occupation_id");

ALTER TABLE "relationships" ADD FOREIGN KEY ("record_id") REFERENCES "census_records" ("record_id");

ALTER TABLE "families" ADD FOREIGN KEY ("relationship_id") REFERENCES "relationships" ("relationship_id");
